# Generated by Django 5.0.6 on 2024-07-24 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedsong',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='likedsong',
            constraint=models.UniqueConstraint(fields=('user', 'song_id'), name='unique_user_song'),
        ),
    ]
