# Generated by Django 5.0.6 on 2024-07-29 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
