# Generated by Django 5.0.6 on 2024-08-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
